config/routes.rb
Rails.application.routes.draw do
  root 'pages#new'

resources :pages

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	
  def new
  	@page = Page.new
 end

  def create
  	 @page = Page.create(page_params)
     page_data = Nokogiri::HTML(RestClient.get(@page.page_location))
     data_h1 = page_data.css('h1').children.collect{|e| e.text}.join(",")
     data_h2 = page_data.css('h2').children.collect{|e| e.text}.join(",")
     data_h3 = page_data.css('h3').children.collect{|e| e.text}.join(",")
     data_links = data_links = page_data.css('a').collect{|e| e["href"]}.join(",")
     @page.update_attributes(h1_data: data_h1, h2_data: data_h2, h3_data: data_h3, links_data: data_links)
     redirect_to new_page_path
  end

  def index
  	@pages = Page.all
  end

  def page_params
    params.require(:page).permit(:page_location, :h1_data, :h2_data, :h3_data, :links_data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodingTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<table>
  <thead>
    <tr>
      <th>URL</th>
      <th>H1</th>
      <th>H2</th>
      <th>H3</th>
      <th>links</th>

    </tr>
  </thead>
    <tbody>
      <% @pages.each do |page|%>
        <tr><td><%= page.page_location %></td>
        <td><%= page.h1_data %></td>
        <td><%= page.h2_data %></td>
        <td><%= page.h3_data %></td>
        <td><%= page.links_data %>
        </td></tr>
      <% end %>
    </tbody>
 

   </table>

   <%= link_to 'Back', new_page_path %>

app/views/pages/new.html.erb
<h1>New URL</h1>
 
 <%= link_to 'See History', pages_path %>

<%= form_for @page do |f| %>
 
  <p>
    <%= f.label :page_location %><br>
    <%= f.text_field :page_location %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>